### ISSUE TITLE
使用帮助

### ISSUE THREAD

**Issue by Leowolf93** [hyrious/RpgMakerClipboardAssist#1]
大佬您好，我想请教一下这个的使用说明。
我有一个RpgMaker VX的日文游戏，一直想玩，想将对话拷贝到剪贴板中，再用有道翻译的剪贴板读取工具直接翻译。
下载了您的工具之后运行了，但是控制台和剪贴板都没有出现对话。
是我理解错了这个工具的使用方法，还是我弄错了什么呢？
十分感谢您。

**Comment by hyrious** [comment]
首先这个工具确实没写完，当年开了一半坑就懒得做下一步了 \_(:з」∠)\_

这个工具主要想完成这样一件事情，就是发现 RPG Maker 编辑器里是可以复制粘贴事件、图块等数据的，这些数据存在了系统剪贴板里，这样就能完成不同项目（不同编辑器）之间的复制粘贴操作。但是 RMXP 和 RMVA 的编辑器剪贴板并不互通，这是因为他们剪贴板里的数据格式不同。

经过 Win32API 检查剪贴板里数据后得知，他们实际上是注册了不同的剪贴板缓冲区 (比如调用 `RegisterClipboardFormat("RMXP")` 可以获得一个名叫 RMXP 的缓冲区的 ID，接着调用 `GetClipboardData(上一步获得的 ID)` 可以得到这个缓冲区里的二进制数据)。对于 RMXP ~ RMVA 这三作编辑器而言，他们的剪贴板数据就是一个比较干净的 Ruby Marshal，可以直接通过 Ruby 代码 `Marshal.load(data)` 解读；对于 RMMV、RMMZ 则是存的 JSON。

所以当年我的想法是通过自动把剪贴板里出现的 RMXP 数据翻译成 RMVA 数据再写入剪贴板，就可以实现从 RMXP 编辑器直接移植事件等数据的能力了。实际上当时已经存在一个工具可以把整个 RMXP 项目翻译成 RMVA 项目。类似的，通过读写剪贴板也可以把 RM 编辑器里比较复杂的操作在额外制作一个编辑器实现批量写入。以往的外部编辑器通常需要你重启 RM 才能生效 (因为 RM 并没有自动监听系统文件变更，要重启才能重新读取项目)，通过这个工具就能稍微加快一点编辑效率。

- - -

对于你玩游戏想自动翻译的需求，我记得当年有个利用屏幕截图 + OCR 实现的万能翻译机但我忘了叫啥，你可以试着找找。如果还是想把游戏对话自动写入剪贴板，首先你需要获得一个未加密的游戏工程，然后编写脚本在 Window_Message 相关的代码增加复制文本的代码，相关 Win32API 你可以参考本项目里的 `Clipboard.text=()` 实现。

https://github.com/hyrious/RpgMakerClipboardAssist/blob/0a9fb511e1651e0f4fe7b8eb5de89ef1de804fee/Data/clipboard.rb#L63-L67

**Comment by Leowolf93** [comment]
原来如此！感谢大佬细致的回复！！
那个OCR工具不太好用，我在尝试去编写一个可以直接附加程序就可以获取到文本的方式，目前磕磕绊绊的哈哈哈_(:з」∠)_
